# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dcab9a62eade2f6347ab529ce6cda3b79eb38f2674ad7e5f724d56ca973eeb2c654e91e21f0dd810edf22cf6c1ce617d9335d4254857c0df7172fe463ea3db6

test:
  secret_key_base: 3b8e744552784cd40275607bee8ae079b2249144634ac2d1903a63dea714db25d00b2e0ed989db543e787087164a367c4f227b36a78b165b8c480ce7a35ed66e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
